fix various linter errors
p.haul:41:40: E231 missing whitespace after ','
phaul/fs_haul_ploop.py:54:4: F841 local variable 'receiver' is assigned to but never used
phaul/criu_api.py:52:6: E713 test for membership should be 'not in'
phaul/criu_req.py:126:1: W391 blank line at end of file
phaul/images.py:10:1: F811 redefinition of unused 'time' from line 8
phaul/p_haul_service.py:6:1: F401 'xem_rpc' imported but unused
phaul/p_haul_lxc.py:11:1: F401 'fs_haul_subtree' imported but unused
phaul/p_haul_lxc.py:83:11: E703 statement ends with a semicolon
phaul/p_haul_type.py:18:23: W601 .has_key() is deprecated, use 'in'
phaul/p_haul_iters.py:85:14: E231 missing whitespace after ','
phaul/p_haul_iters.py:171:10: E703 statement ends with a semicolon
phaul/util.py:54:2: F841 local variable 'fd' is assigned to but never used
phaul/xem_rpc_client.py:5:1: F401 'socket' imported but unused
phaul/xem_rpc_client.py:7:1: F401 'util' imported but unused
phaul/xem_rpc.py:10:1: F401 'util' imported but unused
phaul/p_haul_vz.py:9:1: F401 'p_haul_module' imported but unused
Makefile:3: recipe for target 'lint' failed

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>